-- PesteOnline Admin Panel - database foundation
-- Run this file once in Supabase SQL Editor.

alter table if exists public.pistachio_prices
  add column if not exists source text default 'میانگین بازار ایران';

create table if not exists public.daily_prices (
  id bigint generated by default as identity primary key,
  product_id bigint not null,
  price numeric not null,
  source text,
  price_date date not null default current_date,
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique(product_id, price_date)
);

create index if not exists daily_prices_product_date_idx
  on public.daily_prices(product_id, price_date desc);

create table if not exists public.admin_articles (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  excerpt text,
  content text,
  cover_image text,
  content_type text not null default 'article' check (content_type in ('article','news','analysis')),
  status text not null default 'draft' check (status in ('draft','published')),
  meta_title text,
  meta_description text,
  canonical_url text,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  setting_key text unique not null,
  setting_value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.daily_prices enable row level security;
alter table public.admin_articles enable row level security;
alter table public.site_settings enable row level security;

-- Authenticated admin can manage admin data.
create policy "authenticated manage daily prices" on public.daily_prices
  for all to authenticated using (true) with check (true);
create policy "authenticated manage articles" on public.admin_articles
  for all to authenticated using (true) with check (true);
create policy "authenticated manage site settings" on public.site_settings
  for all to authenticated using (true) with check (true);

-- Public website may read only published information.
create policy "public read daily prices" on public.daily_prices
  for select to anon using (true);
create policy "public read published articles" on public.admin_articles
  for select to anon using (status = 'published');
create policy "public read settings" on public.site_settings
  for select to anon using (true);
